title: Settings
fields:
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: page_class
    field:
      options:
        page-privacy: Impressum/Datenschutz
      type: select
      display: 'Seiten CSS-Klasse'
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
